In [1]:
import pandas as pd

In [2]:
f=pd.read_csv("house_price_analysis.csv")
df=pd.DataFrame(f)
df

,Area,Bedrooms,Bathrooms,Age,Parking,LocationScore,Price
0,900,2,1,10,1,6,3200000
1,1100,2,2,8,1,7,4200000
2,1400,3,2,6,1,8,5500000
3,1600,3,3,5,2,9,6800000
4,1800,4,3,4,2,9,7600000
5,1000,2,1,12,1,6,3500000
6,1250,3,2,7,1,7,4900000
7,1500,3,2,5,2,8,6100000
8,1700,4,3,3,2,9,7300000
9,2000,4,4,2,3,10,9200000


In [3]:
df.head()

,Area,Bedrooms,Bathrooms,Age,Parking,LocationScore,Price
0,900,2,1,10,1,6,3200000
1,1100,2,2,8,1,7,4200000
2,1400,3,2,6,1,8,5500000
3,1600,3,3,5,2,9,6800000
4,1800,4,3,4,2,9,7600000


In [4]:
df.shape

(15, 7)

In [5]:
df.columns

Index(['Area', 'Bedrooms', 'Bathrooms', 'Age', 'Parking', 'LocationScore',
       'Price'],
      dtype='object')

In [6]:
df.dtypes

Area             int64
Bedrooms         int64
Bathrooms        int64
Age              int64
Parking          int64
LocationScore    int64
Price            int64
dtype: object

In [7]:
df.isnull().sum()

Area             0
Bedrooms         0
Bathrooms        0
Age              0
Parking          0
LocationScore    0
Price            0
dtype: int64

In [8]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
dtype: bool

In [9]:
df.describe()

,Area,Bedrooms,Bathrooms,Age,Parking,LocationScore,Price
count,15.000000,15.000000,15.000000,15.00000,15.000000,15.00000,1.500000e+01
mean,1463.333333,3.133333,2.400000,5.80000,1.666667,8.00000,6.033333e+06
std,374.388390,0.915475,0.985611,3.27763,0.723747,1.36277,2.047530e+06
min,900.000000,2.000000,1.000000,1.00000,1.000000,6.00000,3.200000e+06
25%,1175.000000,2.500000,2.000000,3.50000,1.000000,7.00000,4.550000e+06
50%,1500.000000,3.000000,2.000000,5.00000,2.000000,8.00000,6.100000e+06
75%,1725.000000,4.000000,3.000000,7.50000,2.000000,9.00000,7.400000e+06
max,2100.000000,5.000000,4.000000,12.00000,3.000000,10.00000,9.800000e+06


## Part C

### Linear Regression

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error

In [11]:
x=df[["Area"]]
y=df["Price"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model=LinearRegression()
model.fit(x_train,y_train)
pre=model.predict(x_test)
acc=r2_score(y_test,pre)
mse=mean_squared_error(y_test,pre)
print("Accuracy",acc)
print("MSE",mse)

Accuracy 0.9906476551249069
MSE 58192368111.69043


In [12]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error
x1=df.drop("Price",axis=1)
y1=df["Price"]
x1_train,x1_test,y1_train,y1_test=train_test_split(x1,y1,test_size=0.2,random_state=42)
model1=LinearRegression()
model1.fit(x1_train,y1_train)
pre1=model1.predict(x1_test)
acc1=r2_score(y1_test,pre1)
mse1=mean_squared_error(y1_test,pre1)
print("Accuracy",acc1)
print("MSE",mse1)

Accuracy 0.9981179806604562
MSE 11710342557.161705


### Polynomial regression

In [13]:
from sklearn.preprocessing import PolynomialFeatures

In [14]:
x2=df[["Area"]]
y2=df["Price"]
x2_train,x2_test,y2_train,y2_test=train_test_split(x2,y2,test_size=0.2,random_state=42)
poly=PolynomialFeatures(degree=3)
x_poly_train=poly.fit_transform(x2_train)
x_poly_test=poly.transform(x2_test)
model2=LinearRegression()
model2.fit(x_poly_train,y2_train)
pre2=model2.predict(x_poly_test)
acc2=r2_score(y2_test,pre2)
mse2=mean_squared_error(y2_test,pre2)
print("Accuracy",acc2)
print("MSE",mse2)

Accuracy 0.994479351788867
MSE 34350699980.38283


### 🔹 Part D: Classification Models (7 Marks)

In [15]:
df

,Area,Bedrooms,Bathrooms,Age,Parking,LocationScore,Price
0,900,2,1,10,1,6,3200000
1,1100,2,2,8,1,7,4200000
2,1400,3,2,6,1,8,5500000
3,1600,3,3,5,2,9,6800000
4,1800,4,3,4,2,9,7600000
5,1000,2,1,12,1,6,3500000
6,1250,3,2,7,1,7,4900000
7,1500,3,2,5,2,8,6100000
8,1700,4,3,3,2,9,7300000
9,2000,4,4,2,3,10,9200000


In [16]:
median=df["Price"].median()
median

6100000.0

In [17]:
import numpy as np
df["Target"]=np.where((df["Price"]>median),1,0)

In [18]:
df

,Area,Bedrooms,Bathrooms,Age,Parking,LocationScore,Price,Target
0,900,2,1,10,1,6,3200000,0
1,1100,2,2,8,1,7,4200000,0
2,1400,3,2,6,1,8,5500000,0
3,1600,3,3,5,2,9,6800000,1
4,1800,4,3,4,2,9,7600000,1
5,1000,2,1,12,1,6,3500000,0
6,1250,3,2,7,1,7,4900000,0
7,1500,3,2,5,2,8,6100000,0
8,1700,4,3,3,2,9,7300000,1
9,2000,4,4,2,3,10,9200000,1


### 4️⃣ KNN Classifier

In [19]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,precision_score,recall_score,f1_score

In [20]:
x=df.drop("Target",axis=1)
y=df["Target"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model=KNeighborsClassifier(n_neighbors=3)
model.fit(x_train,y_train)
pre=model.predict(x_test)
acc=accuracy_score(y_test,pre)
f1=f1_score(y_test,pre)
recall=recall_score(y_test,pre)
precision=precision_score(y_test,pre)
CN=confusion_matrix(y_test,pre)
c1=classification_report(y_test,pre)
print(acc)
print(f1)
print(recall)
print(precision)
print(CN)
c1

1.0
1.0
1.0
1.0
[[2 0]
 [0 1]]


'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00         2\n           1       1.00      1.00      1.00         1\n\n    accuracy                           1.00         3\n   macro avg       1.00      1.00      1.00         3\nweighted avg       1.00      1.00      1.00         3\n'

In [21]:
from sklearn.tree import DecisionTreeClassifier

In [22]:
x=df.drop("Target",axis=1)
y=df["Target"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model=DecisionTreeClassifier(criterion="entropy")
model.fit(x_train,y_train)
pre=model.predict(x_test)
acc=accuracy_score(y_test,pre)
f1=f1_score(y_test,pre)
recall=recall_score(y_test,pre)
precision=precision_score(y_test,pre)
CN=confusion_matrix(y_test,pre)
c1=classification_report(y_test,pre)
print(acc)
print(f1)
print(recall)
print(precision)
print(CN)
c1

1.0
1.0
1.0
1.0
[[2 0]
 [0 1]]


'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00         2\n           1       1.00      1.00      1.00         1\n\n    accuracy                           1.00         3\n   macro avg       1.00      1.00      1.00         3\nweighted avg       1.00      1.00      1.00         3\n'

### Part E: Final Comparison using DataFrames (3 Marks)

In [23]:
data={
    "Model":["Simple LR","Multi LR","Polynomial"],
    "MSE":[mse,mse1,mse2],
    "r2_score":[acc,acc1,acc2]
}
df1=pd.DataFrame(data)
df1

,Model,MSE,r2_score
0,Simple LR,5.819237e+10,1.000000
1,Multi LR,1.171034e+10,0.998118
2,Polynomial,3.435070e+10,0.994479


In [24]:
f=pd.read_csv("Churn.csv")
df=pd.DataFrame(f)
df.isnull().sum()
df=df.fillna(df["TotalCharges"].mean())

In [25]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [26]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,precision_score,recall_score,f1_score
from sklearn.model_selection import train_test_split

In [27]:
df=df.drop("customerID",axis=1)

In [28]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes


In [29]:
x=df.drop("Churn",axis=1)
y=df["Churn"]
x=pd.get_dummies(x)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
data={}
for i in range(1,20):
    model=KNeighborsClassifier(n_neighbors=i)
    model.fit(x_train,y_train)
    pre=model.predict(x_test)
    acc=accuracy_score(y_test,pre)
    data[i]=acc
# print(data)
max_key = max(data, key=data.get)
print(max_key)

13


In [30]:
model=KNeighborsClassifier(n_neighbors=max_key)
model.fit(x_train,y_train)
pre=model.predict(x_test)
acc=accuracy_score(y_test,pre)
f1=f1_score(y_test,pre,pos_label="Yes")
recall=recall_score(y_test,pre,pos_label="Yes")
precision=precision_score(y_test,pre,pos_label="Yes")
CN=confusion_matrix(y_test,pre)
c1=classification_report(y_test,pre)
print(acc)
print(f1)
print(recall)
print(precision)
print(CN)
print(c1)

0.7991483321504613
0.5428109854604201
0.450402144772118
0.6829268292682927
[[958  78]
 [205 168]]
              precision    recall  f1-score   support

          No       0.82      0.92      0.87      1036
         Yes       0.68      0.45      0.54       373

    accuracy                           0.80      1409
   macro avg       0.75      0.69      0.71      1409
weighted avg       0.79      0.80      0.78      1409



In [31]:
x=df.drop("Churn",axis=1)
y=df["Churn"]
x=pd.get_dummies(x)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
data={}
for i in range(1,20):
    model=DecisionTreeClassifier(max_depth=i)
    model.fit(x_train,y_train)
    pre=model.predict(x_test)
    acc=accuracy_score(y_test,pre)
    data[i]=acc
# print(data)
max_key = max(data, key=data.get)
print(max_key)

6


In [32]:
model=DecisionTreeClassifier(criterion="entropy",max_depth=max_key)
model.fit(x_train,y_train)
pre=model.predict(x_test)
acc=accuracy_score(y_test,pre)
f1=f1_score(y_test,pre,pos_label="Yes")
recall=recall_score(y_test,pre,pos_label="Yes")
precision=precision_score(y_test,pre,pos_label="Yes")
CN=confusion_matrix(y_test,pre)
c1=classification_report(y_test,pre)
print(acc)
print(f1)
print(recall)
print(precision)
print(CN)
print(c1)

0.8069552874378992
0.592814371257485
0.5308310991957105
0.6711864406779661
[[939  97]
 [175 198]]
              precision    recall  f1-score   support

          No       0.84      0.91      0.87      1036
         Yes       0.67      0.53      0.59       373

    accuracy                           0.81      1409
   macro avg       0.76      0.72      0.73      1409
weighted avg       0.80      0.81      0.80      1409

