# Numpy

In [1]:
import numpy as np

### 1D Array

In [2]:
a=np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
print(type(a))

<class 'numpy.ndarray'>


### 2D Array

In [7]:
b=np.array([[1,2,3],[4,5,6]])

In [8]:
print(b)

[[1 2 3]
 [4 5 6]]


### 3D Array

In [11]:
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])

In [12]:
print(c)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


In [14]:
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]],dtype=float)

In [15]:
print(c)

[[[1. 2. 3.]
  [4. 5. 6.]]

 [[7. 8. 9.]
  [1. 2. 3.]]]


In [16]:
print(a)
print(a.shape)
print(a.ndim)
print(a.itemsize)
print(a.dtype)
print(a.size)

[1 2 3 4]
(4,)
1
4
int32
4


In [17]:
print(b)
print(b.shape)
print(b.ndim)
print(b.itemsize)
print(b.dtype)
print(b.size)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
4
int32
6


In [18]:
print(c)
print(c.shape)
print(c.ndim)
print(c.itemsize)
print(c.dtype)
print(c.size)

[[[1. 2. 3.]
  [4. 5. 6.]]

 [[7. 8. 9.]
  [1. 2. 3.]]]
(2, 2, 3)
3
8
float64
12


In [19]:
np.__version__

'1.26.4'

In [21]:
a=np.arange(12)
b=np.arange(1,4)
c=np.arange(1,8,2)

print(a)
print(b)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[1 2 3]
[1 3 5 7]


#### Scalar operation

In [24]:
print(a+3)
print(a-3)
print(a/3)
print(a//3)
print(a*3)
print(a**3)


[ 3  4  5  6  7  8  9 10 11 12 13 14]
[-3 -2 -1  0  1  2  3  4  5  6  7  8]
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.         3.33333333 3.66666667]
[0 0 0 1 1 1 2 2 2 3 3 3]
[ 0  3  6  9 12 15 18 21 24 27 30 33]
[   0    1    8   27   64  125  216  343  512  729 1000 1331]


In [25]:
l=[1,2,3]
b=l
b[1]=100
l

[1, 100, 3]

### Reshape
```
It changes the dimensions of a given array provided by the parameter
```

In [26]:
a=np.arange(12).reshape(3,4)

In [27]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
a=np.arange(12).reshape(6,2)

In [29]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [30]:
a=np.arange(12).reshape(2,2,3)

In [31]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [32]:
a=np.arange(12).reshape(4,1,3)

In [33]:
a

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [34]:
a=np.arange(12).reshape(6,1,2)

In [35]:
a

array([[[ 0,  1]],

       [[ 2,  3]],

       [[ 4,  5]],

       [[ 6,  7]],

       [[ 8,  9]],

       [[10, 11]]])

#### Iterating through the array

In [36]:
for i in a:
    print(i)

[[0 1]]
[[2 3]]
[[4 5]]
[[6 7]]
[[8 9]]
[[10 11]]


In [37]:
for i in a:
    for j in i:
        print(j)

[0 1]
[2 3]
[4 5]
[6 7]
[8 9]
[10 11]


In [38]:
for i in a:
    for j in i:
        for k in j:
            print(k)

0
1
2
3
4
5
6
7
8
9
10
11


In [39]:
for i in np.nditer(a):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


##### np.concatenate
```
.It joins two given array at a given axis
```

In [40]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [41]:
np.concatenate((c,d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [42]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [54]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

##### np.array_split
```
.It is opposite to join; will split the given array into given split
.For an array of length l that should be split
    into n sections, it returns l % n sub-arrays of size l//n + 1
    and the rest of size l//n.
```

In [ ]:
np.array_split??

In [56]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


#### np.where
```
.It returns the indices of the given array 

In [47]:
a=np.array([40,3,32,654,42,65,43,65])

In [48]:
np.where(a>50)

(array([3, 5, 7], dtype=int64),)

In [49]:
np.where(a>50,0,a)

array([40,  3, 32,  0, 42,  0, 43,  0])

In [50]:
np.where(a%2==0,0,a)

array([ 0,  3,  0,  0,  0, 65, 43, 65])

##### np.sort
```
. It sorts the given array based on the given asix

In [1]:
class Test:
    def __init__(self):
        self.x = 0
class Derived_Test(Test):
    def __init__(self):
        self.y = 1
def main():
     b = Derived_Test()
     print(b.x,b.y)
main()

AttributeError: 'Derived_Test' object has no attribute 'x'

In [2]:
class Demo:
    def __init__(self):
        self.x = 1
    def change(self):
        self.x = 10
class Demo_derived(Demo):
    def change(self):
        self.x=self.x+1
        return self.x
def main():
    obj = Demo_derived()
    print(obj.change())

main()

2
